---

language: ruby
sudo: required
services:
  - docker
install:
  - docker pull franklinkim/ansible:ubuntu-trusty
  - docker pull franklinkim/ansible:ubuntu-precise
script:
  - docker run -v $(pwd):/opt/ansible franklinkim/ansible:ubuntu-trusty tests/run.sh
  - docker run -v $(pwd):/opt/ansible franklinkim/ansible:ubuntu-precise tests/run.sh
