---

- name: Configuring MySQL
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart mysql
  with_items:
    - etc/mysql/my.cnf

- name: Setting the root password
  mysql_user:
    user: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  when: ansible_hostname != 'localhost'
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost

- name: Seting the root password
  mysql_user:
    user: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  when: ansible_hostname == 'localhost'
  with_items:
   - 127.0.0.1
   - ::1
   - localhost

- name: Configuring easy root access
  template:
    src: root/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: "0600"

- name: Removing anonymous users
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_hostname }}"
    - localhost

- name: Removing test database
  mysql_db:
    name: test
    state: absent
