---

- name: Managing users
  mysql_user:
    append_privs: 		"{{ item.append_privs | default(omit) }}"
    host: 						"{{item.host | default(omit) }}"
    name: 						"{{ item.name }}"
    password: 				"{{ item.password | default(omit) }}"
    priv: 						"{{ item.priv | default(omit) }}"
    state: 						"{{ item.state | default(omit) }}"
    update_password: 	"{{ item.update_password | default(omit) }}"
  with_items: "{{ mysql_users }}"
